import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import CartContextProvider from "./context/cartContextProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <Navbar/>
            <main className="h-full max-h-full">{children}</main>
          <Footer/>
        </CartContextProvider>
      </body>
    </html>
  );
}
